### ISSUE TITLE
please push a release tag

### ISSUE THREAD

**Issue by rbtcollins** [tokio-rs/tracing-opentelemetry#113]
The workflow https://github.com/tokio-rs/tracing-opentelemetry/blob/v0.1.x/.github/workflows/release.yml will upload to cargo if someone can push a tag :) 

The otel release can't be fully consumed in the ecosystem until this bridge crate releases!

**Comment by jtescher** [comment]
Done 👍  https://github.com/tokio-rs/tracing-opentelemetry/releases/tag/v0.23.0

**Comment by rbtcollins** [comment]
Thank you!
