### ISSUE TITLE
`tracing::error!` does not set the level to ERROR

### ISSUE THREAD

**Issue by nastynaz** [tokio-rs/tracing-opentelemetry#125]
I noticed that `tracing::error!(...)` inside a span will set the span level to error, but the event it emits itself is left as `level = information`. How can I make it so that it creates error events with the correct level?

Example:
```rust
#[tracing::instrument]
async fn foo() {
    tracing::error!("request rejected");
}
```
The above will mark the span `foo` as level error, but also emit an event with the message "request rejected" that is of level information.

Any ideas how to fix this?

**Comment by mladedav** [comment]
What do you mean by level here? Where do you see it?

If you're looking at logs emitted by `tracing` by another `Subscribe` implementation (e.g. `FmtSubscriber`) those should have correct level. There even isn't a mechanism by which the level could be changed by this library.

If you're looking at events inside a span in Jaeger or Tempo, where do you see the level? As far as I know there isn't a notion of level or severity for events inside a span.

**Comment by nastynaz** [comment]
@mladedav Thanks for your reply. I realised I should have RTFM before posting this. After reading the OTEL spec I now understand that spans have a `status` that can error but - as you rightly said - there's no notion of severity for events. I'd wrongly assumed that `tracing `and OTEL thought of traces in the same way.
