### ISSUE TITLE
Support OpenTelemetry 0.24

### ISSUE THREAD

**Issue by NOBLES5E** [tokio-rs/tracing-opentelemetry#154]
The upcoming release of OpenTelemetry 0.24 (https://github.com/open-telemetry/opentelemetry-rust/pull/1932) introduces breaking changes that affect the current implementation of `tracing-opentelemetry`.

Please update `tracing-opentelemetry` to support OpenTelemetry 0.24. This will ensure continued compatibility and allow users to benefit from the latest OpenTelemetry features and improvements.

**Comment by djc** [comment]
Of course we will. Are you able to submit a PR?

**Comment by NOBLES5E** [comment]
I've encountered a challenge: OpenTelemetry 0.24 has made `Tracer::provider()` private, which impacts the current implementation. Given my limited familiarity with the tracing-opentelemetry codebase, I'm not confident in proposing a workaround for this change.

**Comment by djc** [comment]
I wrote up some feedback for upstream here:

https://github.com/open-telemetry/opentelemetry-rust/pull/1755#issuecomment-2226902662

**Comment by NOBLES5E** [comment]
Today opentelemetry 0.24 was released. However the sampler is still private which seems to break this line: https://github.com/tokio-rs/tracing-opentelemetry/blob/7f4409a935608bb89e970956217a91945f285b0f/src/tracer.rs#L82

**Comment by djc** [comment]
Thanks for letting me know. See https://github.com/tokio-rs/tracing-opentelemetry/pull/155 and https://github.com/open-telemetry/opentelemetry-rust/pull/1937.

**Comment by NOBLES5E** [comment]
Thanks!
