### ISSUE TITLE
Tracing with opentelemetry-datadog

### ISSUE THREAD

**Issue by open-schnick** [tokio-rs/tracing-opentelemetry#18]
### Version

opentelemetry = { version = "0.19.0", features = ["rt-tokio"] }
opentelemetry-datadog = { version = "0.7.0", features = ["reqwest-client"] }
tracing = "0.1.38"
tracing-opentelemetry = "0.18.0"
tracing-subscriber = "0.3.17"

### Description

Hi,
i am having quite the difficulties getting the opentelemetry ecosystem to run.
First of all i am getting compiler errors when running the basic example from the readme

error[E0277]: the trait bound `opentelemetry::sdk::trace::Tracer: opentelemetry_api::trace::tracer::Tracer` is not satisfied

let telemetry = tracing_opentelemetry::layer().with_tracer(tracer);
    |                                                    ----------- ^^^^^^ the trait `opentelemetry_api::trace::tracer::Tracer` is not implemented for opentelemetry::sdk::trace::Tracer`

But looking at the error it seems that is more a opentelemetry error than a problem of this crate.

But my actual problem is, that i dont know how to integrate tracing-opentelemetry with opentelemetry-datadog
I have this code where i supllemented the "regular" tracer with the datadog tracer using following code:

```rust
    let tracer = new_pipeline()
        .install_batch(opentelemetry::runtime::Tokio)
        .unwrap();

    let telemetry = tracing_opentelemetry::layer().with_tracer(tracer);
    Registry::default().with(telemetry).init();
```
This results in the following compile error:
error[E0277]: the trait bound `opentelemetry::sdk::trace::Tracer: opentelemetry_api::trace::tracer::Tracer` is not satisfied

let telemetry = tracing_opentelemetry::layer().with_tracer(tracer);
   
the trait `opentelemetry_api::trace::tracer::Tracer` is not implemented for `opentelemetry::sdk::trace::Tracer`

Can anyone point me in the right direction?
Is this a opentelemetry, tracing-opentelemetry oder opentelemetry-datadog bug?
Or is it lack of documentation?

**Comment by davidbarsky** [comment]
`tracing-opentelemetry` currently depends on `opentelemetry 0.18`; we'll get it to 0.19 shortly. In the meantime, I'd suggest downgrading to `opentelemetry 0.18`—this should fix your issue.
