### ISSUE TITLE
Export level as custom span attribute

### ISSUE THREAD

**Issue by mTsBucy1** [tokio-rs/tracing-opentelemetry#180]
### Motivation

I would like to use an opentelemetry backend to collect most of my traces. However, I would also like to be able to glance at them and only see important happenings. `tracing` has the nice concept of levels for this usecase, opentelemetry does not natively, but has custom fields.
This is in relation to the discussion #177.

### Proposal

I propose to also attach the `level` of a `tracing span` to the opentelemetry span.
As far as I can entail, this would been adding an `builder_attrs.push(KeyValue::new("level", attrs.metadata().level()));` to [Layer::on_new_span](https://github.com/tokio-rs/tracing-opentelemetry/blob/v0.1.x/src/layer.rs#L846) and possibliy adding a setting to enable this.
(this might be breaking, if it overrides custom "level" attributes).

I'm happy to make this change, but wanted to ask for feedback fist.

### Alternatives

Alternatively, one could always attach an own field, but this entails a lot of duplication.

**Comment by djc** [comment]
I'm open to reviewing a PR for this.

**Comment by mTsBucy1** [comment]
Closed by #182
