### ISSUE TITLE
Docs Outdated with V0.20?

### ISSUE THREAD

**Issue by stephenandary** [tokio-rs/tracing-opentelemetry#46]
## Bug Report

Following getting started docs imports, I get: 

![image](https://github.com/tokio-rs/tracing-opentelemetry/assets/12686470/9f2ce74b-ba88-43ea-a3a0-738a8c6b2427)

I have yet to dig into changes, and additional docs, but this was not an issue in 0.19.0

Cargo.toml deps related to tracing: 
![image](https://github.com/tokio-rs/tracing-opentelemetry/assets/12686470/2fa064e4-fd79-43d4-a048-3fc94f1f1aa5)

### Version
v0.20.0

**Comment by stephenandary** [comment]
Going to use Dependencies as they are in the cargo.toml here and see what happens first.

**Comment by stephenandary** [comment]
Please include updated documentation indicating the correct dependencies required to use this crate. I have tried to include dependencies in various ways based on what I expect I should need to do, and what is done within this crate. I still hit a lot of issues. 

A cargo.toml showing what to use as a user would go a long way to not hitting so many issues.

**Comment by jtescher** [comment]
Yeah the readme needs to be updated, the lib docs are correct. Do you have time to submit a PR to fix the readme to look more like https://github.com/tokio-rs/tracing-opentelemetry/blob/6bc7dce9560111374dba3ba38e8fdfc257e23541/src/lib.rs#L54C2-L80?

**Comment by stephenandary** [comment]
Not at the moment. I am not currently working on tracing, I just saw the
compile errors today while working on other things as I brought in the
crate for later. I should be able to do so in a week or 2, but not sure
exactly when at the moment.

**Comment by ymgyt** [comment]
I'll try it.

**Comment by jtescher** [comment]
Resolved in #47
