### ISSUE TITLE
Question: how to use otel global::tracer_prover with tracing crate

### ISSUE THREAD

**Issue by trend-amikai-chuang** [tokio-rs/tracing-opentelemetry#63]
# Motivation

I would like to inquire about using the global tracer in the OpenTelemetry crate with the Tracing crate. The global tracer provider returns a [BoxedTrace](https://docs.rs/opentelemetry/latest/opentelemetry/global/struct.BoxedTracer.html). However, it does not seem to implement the PreSampledTracer interface. 

Is there a possible workaround for this situation?

Please note that I am aware that I can use `opentelemetry::sdk::trace::Tracer`. However, in my code design, I prefer to use the global tracer for the sake of simplicity.

```rust
let tracer = opentelemetry_api::global::tracer_provider().tracer("example");
let traceing_layer = OpenTelemetryLayer::new(tracer);
```

```
error[E0277]: the trait bound `BoxedTracer: PreSampledTracer` is not satisfied
   --> crates/server/src/monitor.rs:24:50
    |
24  |     let traceing_layer = OpenTelemetryLayer::new(tracer);
    |                          ----------------------- ^^^^^^ the trait `PreSampledTracer` is not implemented for `BoxedTracer`
    |                          |
    |                          required by a bound introduced by this call
    |
    = help: the following other types implement trait `PreSampledTracer`:
              NoopTracer
              opentelemetry::sdk::trace::Tracer
```

**Comment by jtescher** [comment]
This crate currently only supports the latest `opentelemetry` version. You will get the above error if you are using an older or otherwise mismatching version.
