### ISSUE TITLE
Top-level custom attributes

### ISSUE THREAD

**Issue by ewrogers** [tokio-rs/tracing-opentelemetry#66]
## Feature Request

I want to be able to map custom attributes to top-level keys. It seems that any attribute which is logged will be placed as `attributes.custom.[field_name]`. For example, `info!(environment = "dev")` gets placed into `attributes.custom.environment`.

For this key, I want it to be just `environment` instead of nested, as it makes it much easier to filter. It is okay if certain reserved attributes cannot be mapped in this way (ex: `kind`).

### Motivation

For some providers, like Axiom, this can be problematic to filter on nested fields inside objects.

It would be nice to have certain attributes be available top-level.

### Proposal

In the `tracing` configuration, as this is usually known at initialization time which fields should be mapped in which way. Perhaps with some kind of `with_top_level_attribute(key)` in the builder.

### Alternatives

I have not found a way to get around this, other than trying to create some kind of proxy `Layer` or `Subscriber` that can do the mapping. And this may not work for libraries like `tracing_axiom` which use this library directly.

**Comment by jtescher** [comment]
Top level attributes should be the default. Where are you seeing the `custom` prefix being added?

**Comment by ewrogers** [comment]
After looking into it further, it seems it's an issue with how Axiom [handles trace data](https://axiom.co/docs/query-data/traces). What had confused me is we use their JS library for another project and I was not noticing this behavior.

Turns out, their JS library ships events to a separate API compared to the open-telemetry provider so they are handled differently.

So on their end they toss any "non-recognized" attribute into `attributes.custom`, which is annoying. Will discuss this with them!
