### ISSUE TITLE
Add support for the OpenTelemetry Logging Pipeline

### ISSUE THREAD

**Issue by ewoolsey** [tokio-rs/tracing-opentelemetry#76]
It's fairly unclear to me exactly how this feature works. After a cursory look through the code I'm not exactly sure what's happening when I write:
```rust
info!(log.example = "this is a log", "not sure how this works");
```

In addition, how does this crate interact, if at all, with the Log Pipeline.
Any info would be of great help for me, and likely also in `README`. 

Thanks!

**Comment by ewoolsey** [comment]
Ah Okay so I now understand that `tracing-log` is for compatibility with the `tracing-log` crate. Makes sense. What I was really attempting to get at is if there is any support for the logging OpenTelemetry pipeline. I'm going to change the name of this issue to reflect that.

I'd love to see a discussion on how the logging pipeline could be implemented.

**Comment by ewoolsey** [comment]
For any future people looking for the answer, [opentelemetry-appender-tracing](https://crates.io/crates/opentelemetry-appender-tracing) is the solution. I'm not sure why it's confusingly in a separate crate, but there it is.

**Comment by lpj145** [comment]
The aspect of the implementation of tracing to open telemetry is so weird, omg!!! I'm really frustating with this, we can blow the entire thing and start a new good integration.

**Comment by ewoolsey** [comment]
> The aspect of the implementation of tracing to open telemetry is so weird, omg!!! I'm really frustating with this, we can blow the entire thing and start a new good integration.

Yeah it's all still really fresh. People are making progress though, albeit a little slower than I'd hoped. It's a big project and hard to get right.

**Comment by QAston** [comment]
Does using opentelemetry-appender-tracing conflict in any way with this library?

**Comment by jssblck** [comment]
FWIW, after reading this I decided to just try it and at least in Jaeger logs are shipped as is:
```
fn configure_telemetry_otel(env: Environment, endpoint: &Url) -> Result<()> {
    let export_config = || ExportConfig {
        endpoint: endpoint.as_str().to_string(),
        timeout: Duration::from_secs(5),
        protocol: Protocol::Grpc,
    };
    let resources_config = || {
        Resource::new(vec![
            // https://opentelemetry.io/docs/specs/semconv/resource/
            KeyValue::new("service.name", APP_NAME),
            KeyValue::new("service.version", APP_VERSION),
            KeyValue::new("deployment.environment", env.to_string()),
        ])
    };

    let tracer = opentelemetry_otlp::new_pipeline()
        .tracing()
        .with_exporter(
            opentelemetry_otlp::new_exporter()
                .tonic()
                .with_export_config(export_config()),
        )
        .with_trace_config(
            opentelemetry_sdk::trace::config()
                .with_sampler(Sampler::AlwaysOn)
                .with_id_generator(RandomIdGenerator::default())
                .with_resource(resources_config()),
        )
        .install_batch(opentelemetry_sdk::runtime::Tokio)
        .context("install otel tracer")?;
    let metric = opentelemetry_otlp::new_pipeline()
        .metrics(opentelemetry_sdk::runtime::Tokio)
        .with_exporter(
            opentelemetry_otlp::new_exporter()
                .tonic()
                .with_export_config(export_config()),
        )
        .with_resource(resources_config())
        .with_period(Duration::from_secs(5))
        .with_timeout(Duration::from_secs(10))
        .with_aggregation_selector(DefaultAggregationSelector::new())
        .with_temporality_selector(DefaultTemporalitySelector::new())
        .build()
        .context("install otel metrics collector")?;

    let bridge_tracing = tracing_opentelemetry::layer().with_tracer(tracer);
    let bridge_metrics = tracing_opentelemetry::MetricsLayer::new(metric);

    tracing_subscriber::registry()
        .with(LevelFilter::INFO)
        // Export to the otel trace bridge
        .with(bridge_tracing)
        // Export to the otel metrics bridge
        .with(bridge_metrics)
        // Collect traces to report with errors
        .with(tracing_error::ErrorLayer::default())
        // Collect traces to export to the terminal
        .with(
            tracing_subscriber::fmt::layer()
                .pretty()
                .with_file(false)
                .with_line_number(false),
        )
        .try_init()
        .context("configure local tracing subscriber")
}
```

**Comment by QAston** [comment]
I've tried this too, and the situation is as follows:
* jaeger will not get events outside of spans no matter the configuration because it only supports reading tracing input
* to get log stream output and tracing output you need both this crate and opentelemetry-appender-tracing, as they produce separate data streams
* you need a service that can accept both streams like uptrace (which I use) or signoz, and configure both tracing and logger configurations to get all of the logs
