### ISSUE TITLE
`Display` attribute not showing up in exported metrics

### ISSUE THREAD

**Issue by KentaKudo** [tokio-rs/tracing-opentelemetry#81]
I'm wondering if this is a bug or a feature. Please allow me to raise this as a bug report in case it's an expected behaviour.

### Version

```sh
$ cargo tree | grep tracing-opentelemetry
├── tracing-opentelemetry v0.21.0
```

I'm using v0.21.0 but the same thing should happen for v0.22.0 too.

### Platform

```sh
uname -a
Darwin Kentas-MacBook-Pro-2.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:52 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8112 arm64
```

### Description

Currently `MetricsVisitor` does nothing when `record_debug` is called, which happens when an attribute is given as a variable that implements `Display` (and also `Debug`). This results in missing attributes when exported.

I tried this code:

```rust
tracing::info!(
            counter.myapp.organization = 1,
            %status,
);
```

I expected to see this happen: The attribute `status="active"` is exported as a metrics attribute.

Instead, this happened: The attribute doesn't show up.

The reason why this happens is if an attribute is given as something that implements `Display` trait, it's treated as `DisplayValue`, and from the `tracing-core` crate [`Visitor::record_debug` is visited](https://github.com/tokio-rs/tracing/blob/master/tracing-core/src/field.rs#L593) where `MetricsVisitor` doesn't push it to the attributes slice:

https://github.com/tokio-rs/tracing-opentelemetry/blob/v0.1.x/src/metrics.rs#L148-L150

```rust
fn record_debug(&mut self, _field: &Field, _value: &dyn fmt::Debug) {
        // Do nothing
}
```

I'm wondering if this is an expected behaviour or something that needs to be fixed.

Thank you in advance.

**Comment by jtescher** [comment]
This does appear to be an oversight, should likely have similar behavior as `record_str`. Do you have time to submit a PR to address this?

**Comment by KentaKudo** [comment]
Thank you for looking into this. Sure! Let me try to submit one.
