### ISSUE TITLE
Static span name limitation

### ISSUE THREAD

**Issue by abdolence** [tokio-rs/tracing-opentelemetry#82]
### Motivation

As far as I know currently Span names are required to be `'static str` when we use `span!` macro,
and that's fine for many cases.

However, there are cases when Spans names are generated such as the mainstream approach for HTTP span names:
https://opentelemetry.io/docs/specs/semconv/http/http-spans/#name

Unfortunately attributes on spans in some software (such as GCP) can't replace Span names.

### Proposal

Is there any workarounds to have spans with dynamically allocated strings instead?

**Comment by jtescher** [comment]
Yes, you can use the `otel.name` field which will override the span name in the otel ecosystem. See the special field name docs here https://docs.rs/tracing-opentelemetry/0.22.0/tracing_opentelemetry/#special-fields.
